apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: app-container
        image: 045104524585.dkr.ecr.us-east-1.amazonaws.com/my_app:v1
        env:
          - name: DBHOST
            value: "10.244.0.33"  
          - name: DBPORT
            value: "3306"
          - name: DBUSER
            valueFrom:
                secretKeyRef:
                    name: secrets
                    key: user
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            valueFrom:
                secretKeyRef:
                    name: secrets
                    key: password
          - name: APP_COLOR
            value: "blue"
        ports:
        - containerPort: 8080