apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: sqldb
spec:
  containers:
  - name: db-container
    image: 045104524585.dkr.ecr.us-east-1.amazonaws.com/my_db:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
  dnsPolicy: ClusterFirst
  restartPolicy: Always