apiVersion: v1
kind: Pod
metadata:
    name: app-pod
    namespace: webapp
spec:
  containers:
  - name: app-container
    image: 045104524585.dkr.ecr.us-east-1.amazonaws.com/my_app:v1
    env:
      - name: DBHOST
        value: "10.244.0.26"
      - name: DBPORT
        value: "3306"
      - name: DBUSER
        valueFrom:
          secretKeyRef:
            name: secrets
            key: user
      - name: DATABASE
        value: "employees"
      - name: DBPWD
        valueFrom:
            secretKeyRef:
              name: secrets
              key: password
      - name: APP_COLOR
        value: "blue"
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always