apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  namespace: app-ns
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app-container
        image: 045104524585.dkr.ecr.us-east-1.amazonaws.com/my_app:v1
        env:
          - name: DBHOST
            value: "10.244.0.9"
          - name: DBPORT
            value: "3306"
          - name: DBUSER
            value: "root"
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            value: "pw"
          - name: APP_COLOR
            value: "blue"
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always